### PR TITLE
Add property based test.

### PR DESCRIPTION
**Pull request by mithrandi**
This PR adds a property-based test using Hypothesis, that tests that a patch from a randomly generated source value to a randomly generated destination value is valid (yields the destination value when applied to the source value). This would have been able to find the bug in #55, among other things.

The test is currently failing due to an issue with jsonpointer that I'm not entirely sure how to fix. The first problem is that jsonpointer expects pointers to be urlencoded, which I don't think is correct (my reading of the RFC is that urlencoding should only be used when the pointer is part of a URL, so nothing special to JSON pointer itself). The second issue is that `JsonPointer.from_parts([u'%00'])` ends up generating a pointer of `/\u0000` due to the parts being urldecoded; this is tangled up with the first issue.

I'm happy to do the work to resolve these issues, but I'm not entirely sure what direction to go in, so would appreciate some guidance here. I think the correct thing for jsonpointer to do is to not do any url encoding/decoding at all, but of course this represents a fairly large change in the API.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Thanks for your work! Let me address the issues that you raised:

> The first problem is that jsonpointer expects pointers to be urlencoded, which I don't think is correct 
> (my reading of the RFC is that urlencoding should only be used when the pointer is part of a URL, so 
> nothing special to JSON pointer itself).

I agree that [rfc6901](https://tools.ietf.org/html/rfc6901) does not mention anything about urlencoding, so `jsonpointer` should not expect it. However I'm not sure if I understand you correctly... in `jsonpoiner` I can do the following (without an urlencoded pointer):

````python
>>> import jsonpointer
>>> obj = {'a b': 1}
>>> jsonpointer.resolve_pointer(obj, '/a b')
1
````

Could you please open an issue in [stefankeogl/pyhon-json-pointer](https://github.com/stefankoegl/python-json-pointer/) to describe the issue with an example (or isolated, failing test)?

**Comment by stefankoegl** [comment]
OK, I think I understand your point... rather than the example above, the failing example should be

```python
>>> import jsonpointer
>>> obj = {'a b': 1}
>>> jsonpointer.resolve_pointer(obj, '/a%20b')
1
```

Instead this should give an error because there is no member `a%20b`.

It seems that I added the unquoting (currently [line 145](https://github.com/stefankoegl/python-json-pointer#L145)) already in the very first commit. Initially the [RFC draft|https://tools.ietf.org/html/draft-pbryan-zyp-json-pointer-00] did contain 

>   Property names SHOULD be URI encoded per [RFC2396].  In particular,
>   any "/" character in a property name MUST be encoded as "%2F" to
>    avoid being interpreted as a property reference token separator.

but this was removed in later versions, and is therefore no longer correct.

Would you be interested in submitting a pull request for `jsonpointer` to fix this issue?

**Comment by mithrandi** [comment]
Yup, your example is correct. I'll try to send a PR to `jsonpointer` this week sometime :smiley:

**Comment by stefankoegl** [comment]
I have now added an issue at stefankoegl/python-json-pointer#22.

**Comment by stefankoegl** [comment]
@mithrandi, do you still intend to work on this pull request? The tests are failing for most python versions, but the general idea seems interesting.

**Comment by stefankoegl** [comment]
I will continue the work in #79.

**Comment by mithrandi** [comment]
Sorry, guess I never got back to this! Thanks for picking it up.

**Comment by mithrandi** [comment]
Superseded by #79 I guess.

**Pull request closed without merging**
