### PR TITLE
Allow running certain tests separately

### PR DESCRIPTION
**Pull request by selurvedu**
E.g. `python2 -m unittest tests.MakePatchTestCase.test_objects`
or `nose tests:MakePatchTestCase.test_objects`.

### CODE REVIEW

**Comment by selurvedu** [comment]
That failed build on Python 3.2 doesn't look like my fault (the traceback even doesn't have any mention of `tests.py`). Successful build on other Python versions confirms it.

**Comment by selurvedu** [comment]
I updated the PR (rebased onto `master`) to trigger a new build.

**Comment by stefankoegl** [comment]
Thanks :)

**Comment by selurvedu** [comment]
You're welcome!

**Pull request merged**
