### PR TITLE
if there is no diff print nothing, and exit 2 if a diff is found

### PR DESCRIPTION
**Pull request by gergnz**
To mimic grep and other *nix tools exit non-zero (2 I picked) if a difference is found.  Also print nothing (not even an empty list) if there is no difference.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Hi! Thanks for your contribution :) Is there any precedence for returning 2? I'm asking because it seems kind of arbitrary to me.

**Comment by gergnz** [comment]
Hi @stefankoegl, it was totally arbitrary. I'm happy to take suggestions on a different exit code.

**Comment by gergnz** [comment]
A colleague of mine showed me this http://tldp.org/LDP/abs/html/filearchiv.html#DIFFERR2. I'll change to a 1 and push.

**Comment by stefankoegl** [comment]
Thanks :)

**Pull request merged**
