### PR TITLE
Fix bug in _split_by_common_seq using wrong range in right subtree

### PR DESCRIPTION
**Pull request by apinkney97**
Fixes issue #40

### CODE REVIEW

**Comment by kxepal** [comment]
Nice found!

**Comment by selurvedu** [comment]
Have you checked whether this fixes #30 and #41 as well?

**Comment by apinkney97** [comment]
Neither of them, unfortunately

**Comment by stefankoegl** [comment]
Thanks, merged :)

**Comment by stefankoegl** [comment]
I've just released v1.12 with this fix

**Comment by apinkney97** [comment]
awesome, thanks!

**Pull request merged**
